### ISSUE TITLE
Azure as prerequisite?

### ISSUE THREAD

**Issue by F-Makhokha** [EtienneCoumont/FacebookWebHooks#2]
Hi there I am developing an inhouse application and just wanted to know why do i need Azure, what are the alternative if I just need to buiild a .net app that gets leads and send them to my database.

**Comment by EtienneCoumont** [comment]
Hello. 

Azure is not really mandatory to host the webhook. It's just the simplest and fastest way to test it.

As an alternative, you can host the application on any server that is reachable from the Internet.
Your server has to support ASP.Net 5 Web API and HTTPS.

Edit : Asp.Net 5 has been renamed into ASP.Net Core. The code shown in this project would probably need some change to make it work with the latest ASP.Net Core. I will update it when I get some time.

**Comment by F-Makhokha** [comment]
Thanks  . I have an IS which I can host the Web Application so I suppose  I
should  be good to  deploy the Web hook .

I am very new to facebook development  and I have found it very difficult
 to follow the instructions  from Facebook  development website.

Thanks again.

Regards
Fannie.

**Comment by F-Makhokha** [comment]
Hi I just wanted to know if you manage to get the time to make changes to your code? 

My task is basically getting the leads from the campaign that are running our the facebook ads and write them to database.

**Comment by EtienneCoumont** [comment]
Hi,

I just updated the app to use AspNet Core 2. I also checked that it works with the last version of Facebook WebAPI v2.10

Have fun playing with Facebook Webhooks !
