### ISSUE TITLE
getting only specific fields 

### ISSUE THREAD

**Issue by F-Makhokha** [EtienneCoumont/FacebookWebHooks#3]
Hi @EtienneCoumont  I just wanted to ask , how can I get maybe name, email, phone number and few lead details for my campaign, I'm very new to webhooks and just wanted to save this information as soon as the lead fills my form on the page.

**Comment by EtienneCoumont** [comment]
In summary, with WebHooks, Facebook sends notifications to your server anytime something new happens. 
In your case, you have to subscribe to the "leadgen" event. Then you will recieve a notification for each user that fills in your form.

Basically, the notification contains only an id that you need to extract (the leadgen_id field).
As soon as it recieves the notification, your server has to call the Facebook Graph API, sending the leadgen_id, and will get in return all the information you want (name, email, etc.)

The whole process is explained in details here : https://developers.facebook.com/docs/marketing-api/guides/lead-ads/retrieving

The present repository contains code that can recieve the notification and extract the leadgen_id.
To make calls to the Graph API, you will need another library. The official one is here https://github.com/facebook-csharp-sdk but does not support .Net Core.
Alternative and more details here : http://piotrgankiewicz.com/2017/02/06/accessing-facebook-api-using-c/

Hope it helps.

**Comment by F-Makhokha** [comment]
@EtienneCoumont  how will I make modifications on your code to cater for that?

**Comment by EtienneCoumont** [comment]
Sorry I don't have time to help you more than I did. Please read all the documentations I linked in my previous post. It contains everything you need to know. Then test the code and the tutorial provided on the present repository.
If you have any comments about my implementation or find some bugs in my code, I'll be happy to hear your feedback and fix it.

Best regards.
