### ISSUE TITLE
Cannot Get it to work

### ISSUE THREAD

**Issue by TimCadieux** [EtienneCoumont/FacebookWebHooks#4]
All I ever get is 

error. no match

Do you have a more robust, updated version?

**Comment by EtienneCoumont** [comment]
Hello Tim,

This is a pretty old project. Facebook api has probably changed from then.

I will try to have a look at it when I get some time.

**Comment by EtienneCoumont** [comment]
Thanks for your interest, I have read some docs and took some decisions.

When this project was created, back in 2015, Facebook Webhooks were easy to setup and use. I made this github project to allow developpers to start a small app from scratch than can do cool stuff, like catching a message posted on a Facebook page, and send it via email, post it to Twitter, or anything you could imagine.

Now, using Facebook Webhooks requires passing through an App Review. IMO, this makes this functionality useful only for pretty big existing Facebook apps.

Consequently I don't think this github project will be useful to anyone, and I will not update it.
